name: angola_validator
description: Package para validação  de Bilhete de Identidade(BI), matrícula e IBAN angolano.
version: 0.0.2
homepage: https://github.com/anisioisidoro/flutter_angola_validator

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: